---
# Include varaiables and define needed variables
-name: Include OS-specific variables
 include_vars: "{{ ansible_os_family }}.yaml"

# Install Apache
-name: Ensure Apache is installed on RHEL.
 yum:
   name: "{{ item }}"
   state: installed
 with_items: "{{ apache_packages }}" 
#
#
#
#
-name: httpd.conf file
 template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf

 notify: 
   restart apache service


-name: Ensure Apache has selected state and enabled on boot.
 service:
   name: "{{ apache_service }}"
   state: "{{ apache_state }}"
   enabled: yes
