---

# - hosts: owncloud
# - hosts: groupa
- hosts: wiki
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - common
#
#
# local proxy servers have apache temp fix.
#- hosts: local_proxy
#  roles:
#    - apache
