---
# these can be overridden by the VARs directory vars.
#
# Packages that will be installed as a baseline

# just the common packages across our network
# these will be installed on all machines reguardless
# of their function on the network.

# Packages that will be installed as a baseline
common_packages:
  - vim           # basic text editor
  - bind-utils    # dig ifconfig etc.
#   - puppet        # puppetlabs agent. this is handled by a seperate role
  - htop          # similar to standard top but with more features.
  - net-tools     # Misc networking tools.
  - zip           # archiving tool
  - unzip         # archiving tool
  - gzip          # archiving tool

group_packages: []  # default is empty list this is set in group_vars


# User related vars
#
common_users:
  - puppet
  - testuser1a

common_user_home: /home

