---
# Manage global user account 
#   Non domain
#

- name: Create admin users
  tags:
    - create admin users
  user: name={{ item }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa groups=wheel append=yes
  with_items: "{{ admin_users }}"

- name: Create service users
  tags:
    - create service users
  user: name={{ item }} groups=users append=yes
  with_items: "{{ service_users }}"


- name: Delete list of users
  tags:
    - delete users
  user: name={{ item }} state=absent remove=yes
  with_items:
    - testuser6

