---
# Manage global user account 
#   Non domain
#

- name: Create admin users
  tags:
    - create admin users
  user: name={{ item }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa groups=wheel append=yes
  with_items: "{{ admin_users }}"

- name: Create service users
  tags:
    - create service users
  user: name={{ item }} groups=users append=yes
  with_items: "{{ service_users }}"

- name: Set authorized key, removing all the authorized key already set
  authorized_key:
    user: ggriffiniv  # change this to entuser after testing.
    key: '{{ item }}'
    state: present
    # exclusive: True
  with_file:
    - "{{ playbook_dir }}/keys/id_rsa_global_ent.pub"
    - "{{ playbook_dir }}/keys/id_rsa_ggriffiniv.pub"


#- name: Delete list of users
#  tags:
#    - delete users
#  user: name={{ item }} state=absent remove=yes
#  with_items:
#    - testuser6

