---
# Standard tools and server setup
#   Will need to add some packages over time
#

- name: Install common packages
  tags:
      - install
  yum: name={{ item }} state=present
  with_items: "{{ common_packages }}"
  when: common_packages is defined


- name: Install group packages
  tags:
      - install
  yum: name={{ item }} state=present
  with_items: "{{ group_packages }}"
  when: group_packages is defined


#- name start crit services
#  service: "name={{ item }} state=started enabled=yes"
#  with_items: {{ crit_processes }}
#  when: crit_processes is defined
