---
# Standard tools and server setup
#   Will need to add some packages over time
#

- name: Install common packages
  tags:
      - install
  yum: name={{ item }} state=present
  with_items: "{{ common_packages }}"

- name: Install group packages
  tags:
      - install
  yum: name={{ item }} state=present
  with_items: "{{ group_packages }}"
  when: group_packages is defined


#- name start crit services
#  service: "name={{ item }} state=started enabled=yes"
#  with_items: {{ crit_processes }}
#  when: crit_processes is defined





#- name: Create list of users
#  tags:
#    - create users
#  user: name={{ item }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa groups=wheel append=yes
#  with_items: {{ common_users }}

# - name: Delete list of users
#   tags:
#    - delete users
#  user: name={{ item }} state=absent remove=yes
#  with_items:
#    - testuser6

